---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ActiveCA: Time use data from the general social survey of Canada to study active travel

<!-- badges: start -->
<!-- badges: end -->

-    Bruno Santos, School of Earth, Environment and Society, McMaster University
-    Mahdis Mogadhasi, School of Earth, Environment and Society, McMaster University
-    Antonio Paez, School of Earth, Environment and Society, McMaster University

This paper describes {ActiveCA}, an open data product with Canadian time use data. {ActiveCA} is an R data package that contains analysis-ready data related to active travel spanning almost 40 years, extracted from Cycles 2 (1986), 7 (1992), 12 (1998), 19 (2005), 24 (2010), 29 (2015), and 34 (2022) of the Time Use Survey (TUS) from the General Social Survey (GSS). Active travel episodes are characterized by mode, with walking being part of every cycle and bicycling starting in 1992. The attributes of active trips are the types of locations of origins and destinations, the duration of trips, and episode weights for expanding the trips to population-wide estimates. Based on the year of the survey, a variety of locations are coded. In earlier cycles, these include home, work or school, and other’s home, whereas in later cycles these are augmented with locations such as grocery stores, restaurants, outdoor destinations, and others. The geographical resolution includes the province and whether the episode was in an urban or rural setting. 

https://doi-org.libaccess.lib.mcmaster.ca/10.1177/23998083251374724


## Installation

You can install the development version of ActiveCA from [GitHub](https://github.com/dias-bruno/ActiveCA) with:

``` r
# install.packages("pak")
pak::pak("dias-bruno/ActiveCA")
```
